Avoid traceback in exit plugin if worker build doesn't exist
Following traceback is raised when worker builds are not available

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/atomic_reactor/plugin.py", line 265, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python3.6/site-packages/atomic_reactor/plugins/exit_remove_worker_metadata.py", line 28, in run
    worker_builds = build_result.annotations['worker-builds']
TypeError: 'NoneType' object is not subscriptable
```

Signed-off-by: Martin Bašti <mbasti@redhat.com>